version: '3.9'

services:
  couchbase:
    image: 'couchbase:community-7.1.1'
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    volumes:
      - ./data/couchbase:/opt/couchbase/var